# Generated by Django 4.2 on 2024-10-17 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Attempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_attempt",
                    models.DateField(
                        verbose_name="Дата и время последней попытки рассылки"
                    ),
                ),
                (
                    "status",
                    models.BooleanField(default=False, verbose_name="Статус попытки"),
                ),
                ("server_answer", models.TextField(verbose_name="Ответ сервера")),
            ],
            options={
                "verbose_name": "попытка рассылки",
                "verbose_name_plural": "попытки рассылки",
            },
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Укажите фамилию, имя и отчество клиента",
                        max_length=150,
                        null=True,
                        verbose_name="Ф.И.О",
                    ),
                ),
                (
                    "client_email",
                    models.EmailField(
                        help_text="Укажите электронный адрес клиента",
                        max_length=254,
                        verbose_name="email клиента",
                    ),
                ),
                (
                    "comments",
                    models.CharField(
                        blank=True,
                        help_text="Комментарий",
                        max_length=150,
                        null=True,
                        verbose_name="Комментарий",
                    ),
                ),
            ],
            options={
                "verbose_name": "клиент",
                "verbose_name_plural": "клиенты",
            },
        ),
        migrations.CreateModel(
            name="Owner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=150, verbose_name="Заказчик рассылки"),
                ),
                (
                    "owner_email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="почта заказчика"
                    ),
                ),
            ],
            options={
                "verbose_name": "заказчик",
                "verbose_name_plural": "заказчики",
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "topic",
                    models.CharField(
                        help_text="Укажите название рассылки",
                        max_length=100,
                        verbose_name="Тема письма",
                    ),
                ),
                ("body", models.TextField(verbose_name="Тело письма")),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="distributions.client",
                        verbose_name="Укажите адресатов рассылки",
                    ),
                ),
            ],
            options={
                "verbose_name": "письмо",
                "verbose_name_plural": "письма",
            },
        ),
        migrations.CreateModel(
            name="Distribution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Введите название рассылки",
                        max_length=150,
                        verbose_name="Название",
                    ),
                ),
                (
                    "first_send",
                    models.DateTimeField(
                        help_text="Укажите дату и время первой отправки",
                        verbose_name="Дата и время первой отправки",
                    ),
                ),
                (
                    "period",
                    models.CharField(
                        choices=[
                            ("weekly", "еженедельно"),
                            ("daily", "ежедневно"),
                            ("monthly", "ежемесячно"),
                        ],
                        default="ежедневно",
                        help_text="Укажите период рассылки",
                        max_length=20,
                        verbose_name="Периодичность рассылки",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("completed", "завершена"),
                            ("launched", "запущена"),
                            ("created", "создана"),
                        ],
                        default="created",
                        help_text="Статус рассылки: завершена, создана, запущена",
                        max_length=20,
                        verbose_name="Статус рассылки",
                    ),
                ),
                ("clients", models.ManyToManyField(to="distributions.client")),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="distributions.owner",
                        verbose_name="Заказчик",
                    ),
                ),
            ],
            options={
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
        migrations.AddField(
            model_name="client",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="distributions.owner",
                verbose_name="Заказчик",
            ),
        ),
    ]
