# Generated by Django 4.2 on 2024-10-21 23:32

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("clients", "0001_initial"),
        ("letters", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Distribution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="Название")),
                (
                    "first_send_date",
                    models.DateField(
                        default=datetime.datetime.now,
                        verbose_name="Дата первой отправки",
                    ),
                ),
                (
                    "first_send_time",
                    models.TimeField(
                        default=datetime.datetime.now,
                        verbose_name="Время первой отправки",
                    ),
                ),
                (
                    "period",
                    models.CharField(
                        choices=[
                            ("monthly", "ежемесячно"),
                            ("weekly", "еженедельно"),
                            ("daily", "ежедневно"),
                        ],
                        default="ежедневно",
                        max_length=20,
                        verbose_name="Периодичность рассылки",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("launched", "запущена"),
                            ("created", "создана"),
                            ("completed", "завершена"),
                        ],
                        default="created",
                        max_length=20,
                        verbose_name="Статус рассылки",
                    ),
                ),
                (
                    "clients",
                    models.ManyToManyField(
                        to="clients.client", verbose_name="Адресаты"
                    ),
                ),
                (
                    "letter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="letters.letter",
                        verbose_name="Письмо",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Заказчик",
                    ),
                ),
            ],
            options={
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
    ]
