# Generated by Django 4.2 on 2024-10-21 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("distributions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="distribution",
            name="period",
            field=models.CharField(
                choices=[
                    ("weekly", "еженедельно"),
                    ("monthly", "ежемесячно"),
                    ("daily", "ежедневно"),
                ],
                default="ежедневно",
                max_length=20,
                verbose_name="Периодичность рассылки",
            ),
        ),
        migrations.AlterField(
            model_name="distribution",
            name="status",
            field=models.CharField(
                choices=[
                    ("completed", "завершена"),
                    ("created", "создана"),
                    ("launched", "запущена"),
                ],
                default="created",
                max_length=20,
                verbose_name="Статус рассылки",
            ),
        ),
    ]
