# Generated by Django 4.2 on 2024-10-19 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("distributions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="distribution",
            name="clients",
            field=models.ManyToManyField(
                to="distributions.client", verbose_name="Адресаты"
            ),
        ),
        migrations.AlterField(
            model_name="distribution",
            name="period",
            field=models.CharField(
                choices=[
                    ("monthly", "ежемесячно"),
                    ("daily", "ежедневно"),
                    ("weekly", "еженедельно"),
                ],
                default="ежедневно",
                help_text="Укажите период рассылки",
                max_length=20,
                verbose_name="Периодичность рассылки",
            ),
        ),
        migrations.AlterField(
            model_name="distribution",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "создана"),
                    ("launched", "запущена"),
                    ("completed", "завершена"),
                ],
                default="created",
                help_text="Статус рассылки: завершена, создана, запущена",
                max_length=20,
                verbose_name="Статус рассылки",
            ),
        ),
    ]
