# Generated by Django 4.2 on 2024-10-19 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "distributions",
            "0002_alter_distribution_clients_alter_distribution_period_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="client",
            options={
                "ordering": ("id", "client_email"),
                "verbose_name": "клиент",
                "verbose_name_plural": "клиенты",
            },
        ),
        migrations.AlterField(
            model_name="distribution",
            name="period",
            field=models.CharField(
                choices=[
                    ("weekly", "еженедельно"),
                    ("daily", "ежедневно"),
                    ("monthly", "ежемесячно"),
                ],
                default="ежедневно",
                help_text="Укажите период рассылки",
                max_length=20,
                verbose_name="Периодичность рассылки",
            ),
        ),
    ]
