# Generated by Django 4.2 on 2024-10-22 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("distributions", "0002_alter_distribution_period_alter_distribution_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="distribution",
            name="last_send_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Дата первой отправки"
            ),
        ),
        migrations.AddField(
            model_name="distribution",
            name="last_send_time",
            field=models.TimeField(
                blank=True, null=True, verbose_name="Время первой отправки"
            ),
        ),
        migrations.AlterField(
            model_name="distribution",
            name="period",
            field=models.CharField(
                choices=[
                    ("daily", "ежедневно"),
                    ("weekly", "еженедельно"),
                    ("monthly", "ежемесячно"),
                ],
                default="ежедневно",
                max_length=20,
                verbose_name="Периодичность рассылки",
            ),
        ),
        migrations.AlterField(
            model_name="distribution",
            name="status",
            field=models.CharField(
                choices=[
                    ("launched", "запущена"),
                    ("created", "создана"),
                    ("completed", "завершена"),
                ],
                default="created",
                max_length=20,
                verbose_name="Статус рассылки",
            ),
        ),
    ]
