# Generated by Django 4.2 on 2024-10-22 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("distributions", "0003_distribution_last_send_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="distribution",
            name="last_send_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Дата последней отправки"
            ),
        ),
        migrations.AlterField(
            model_name="distribution",
            name="last_send_time",
            field=models.TimeField(
                blank=True, null=True, verbose_name="Время последней отправки"
            ),
        ),
        migrations.AlterField(
            model_name="distribution",
            name="period",
            field=models.CharField(
                choices=[
                    ("monthly", "ежемесячно"),
                    ("weekly", "еженедельно"),
                    ("daily", "ежедневно"),
                ],
                default="ежедневно",
                max_length=20,
                verbose_name="Периодичность рассылки",
            ),
        ),
    ]
