# Generated by Django 4.2 on 2024-10-20 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0001_initial"),
        ("distributions", "0003_alter_client_options_alter_distribution_period"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="owner",
        ),
        migrations.AlterField(
            model_name="distribution",
            name="clients",
            field=models.ManyToManyField(to="clients.client", verbose_name="Адресаты"),
        ),
    ]
