# Generated by Django 4.2 on 2024-10-23 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("distributions", "0004_alter_distribution_last_send_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="distribution",
            name="period",
            field=models.CharField(
                choices=[
                    ("weekly", "еженедельно"),
                    ("monthly", "ежемесячно"),
                    ("daily", "ежедневно"),
                ],
                default="ежедневно",
                max_length=20,
                verbose_name="Периодичность рассылки",
            ),
        ),
    ]
