# Generated by Django 4.2 on 2024-10-20 22:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "distributions",
            "0005_alter_distribution_owner_alter_distribution_period_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="distribution",
            name="first_send",
        ),
        migrations.AddField(
            model_name="distribution",
            name="first_send_date",
            field=models.DateField(
                default=datetime.datetime.now,
                help_text="Укажите дату первой отправки",
                verbose_name="Дата первой отправки",
            ),
        ),
        migrations.AddField(
            model_name="distribution",
            name="first_send_time",
            field=models.TimeField(
                default=datetime.datetime.now,
                help_text="Укажите время первой отправки",
                verbose_name="Время первой отправки",
            ),
        ),
        migrations.AlterField(
            model_name="distribution",
            name="period",
            field=models.CharField(
                choices=[
                    ("daily", "ежедневно"),
                    ("monthly", "ежемесячно"),
                    ("weekly", "еженедельно"),
                ],
                default="ежедневно",
                help_text="Укажите период рассылки",
                max_length=20,
                verbose_name="Периодичность рассылки",
            ),
        ),
        migrations.AlterField(
            model_name="distribution",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "создана"),
                    ("completed", "завершена"),
                    ("launched", "запущена"),
                ],
                default="created",
                help_text="Статус рассылки: завершена, создана, запущена",
                max_length=20,
                verbose_name="Статус рассылки",
            ),
        ),
    ]
