# Generated by Django 4.2 on 2024-10-24 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "distributions",
            "0006_alter_distribution_owner_alter_distribution_status_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attempt",
            options={
                "ordering": ("last_attempt",),
                "verbose_name": "Отчет",
                "verbose_name_plural": "Отчеты",
            },
        ),
        migrations.AlterField(
            model_name="distribution",
            name="status",
            field=models.CharField(
                choices=[
                    ("launched", "запущена"),
                    ("created", "создана"),
                    ("completed", "завершена"),
                ],
                default="created",
                max_length=20,
                verbose_name="Статус рассылки",
            ),
        ),
    ]
