# Generated by Django 4.2 on 2024-10-21 17:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("distributions", "0006_remove_distribution_first_send_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="distribution",
            name="first_send_date",
            field=models.DateField(
                default=datetime.datetime.now, verbose_name="Дата первой отправки"
            ),
        ),
        migrations.AlterField(
            model_name="distribution",
            name="first_send_time",
            field=models.TimeField(
                default=datetime.datetime.now, verbose_name="Время первой отправки"
            ),
        ),
        migrations.AlterField(
            model_name="distribution",
            name="name",
            field=models.CharField(max_length=150, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="distribution",
            name="period",
            field=models.CharField(
                choices=[
                    ("monthly", "ежемесячно"),
                    ("daily", "ежедневно"),
                    ("weekly", "еженедельно"),
                ],
                default="ежедневно",
                max_length=20,
                verbose_name="Периодичность рассылки",
            ),
        ),
        migrations.AlterField(
            model_name="distribution",
            name="status",
            field=models.CharField(
                choices=[
                    ("completed", "завершена"),
                    ("launched", "запущена"),
                    ("created", "создана"),
                ],
                default="created",
                max_length=20,
                verbose_name="Статус рассылки",
            ),
        ),
    ]
