# Generated by Django 4.2 on 2024-10-26 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("distributions", "0007_alter_attempt_options_alter_distribution_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="distribution",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "создана"),
                    ("completed", "завершена"),
                    ("launched", "запущена"),
                ],
                default="created",
                max_length=20,
                verbose_name="Статус рассылки",
            ),
        ),
    ]
