# Generated by Django 4.2 on 2024-10-26 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("distributions", "0008_alter_distribution_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="distribution",
            name="counter",
            field=models.PositiveIntegerField(
                default=0, editable=False, verbose_name="Количество отправлений"
            ),
        ),
        migrations.AlterField(
            model_name="attempt",
            name="status",
            field=models.CharField(
                choices=[("failed", "неудачно"), ("done", "выполнена")],
                default="failed",
                max_length=20,
                verbose_name="Статус рассылки",
            ),
        ),
        migrations.AlterField(
            model_name="distribution",
            name="period",
            field=models.CharField(
                choices=[
                    ("daily", "ежедневно"),
                    ("weekly", "еженедельно"),
                    ("monthly", "ежемесячно"),
                ],
                default="ежедневно",
                max_length=20,
                verbose_name="Периодичность рассылки",
            ),
        ),
        migrations.AlterField(
            model_name="distribution",
            name="status",
            field=models.CharField(
                choices=[
                    ("completed", "завершена"),
                    ("created", "создана"),
                    ("launched", "запущена"),
                ],
                default="created",
                max_length=20,
                verbose_name="Статус рассылки",
            ),
        ),
    ]
