# Generated by Django 4.2 on 2024-10-26 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("distributions", "0009_distribution_counter_alter_attempt_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="distribution",
            name="next_send_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Дата следующей отправки"
            ),
        ),
        migrations.AddField(
            model_name="distribution",
            name="next_send_time",
            field=models.TimeField(
                blank=True, null=True, verbose_name="Время следующей отправки"
            ),
        ),
        migrations.AlterField(
            model_name="distribution",
            name="period",
            field=models.CharField(
                choices=[
                    ("weekly", "еженедельно"),
                    ("daily", "ежедневно"),
                    ("monthly", "ежемесячно"),
                ],
                default="ежедневно",
                max_length=20,
                verbose_name="Периодичность рассылки",
            ),
        ),
    ]
