# Generated by Django 4.2 on 2024-10-26 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "distributions",
            "0011_alter_attempt_status_alter_distribution_period_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="distribution",
            name="next_send_date",
        ),
        migrations.RemoveField(
            model_name="distribution",
            name="next_send_time",
        ),
        migrations.AddField(
            model_name="distribution",
            name="next_send_datetime",
            field=models.CharField(
                blank=True,
                max_length=30,
                null=True,
                verbose_name="Дата следующей отправки",
            ),
        ),
        migrations.AlterField(
            model_name="attempt",
            name="status",
            field=models.CharField(
                choices=[("failed", "неудачно"), ("done", "выполнена")],
                default="failed",
                max_length=20,
                verbose_name="Статус рассылки",
            ),
        ),
        migrations.AlterField(
            model_name="distribution",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "создана"),
                    ("completed", "завершена"),
                    ("launched", "запущена"),
                ],
                default="created",
                max_length=20,
                verbose_name="Статус рассылки",
            ),
        ),
    ]
