# Generated by Django 4.2 on 2024-10-26 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "distributions",
            "0013_alter_attempt_status_alter_distribution_period_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="distribution",
            name="next_send_datetime",
            field=models.CharField(
                default="", max_length=30, verbose_name="Дата следующей отправки"
            ),
        ),
        migrations.AlterField(
            model_name="distribution",
            name="period",
            field=models.CharField(
                choices=[
                    ("daily", "ежедневно"),
                    ("weekly", "еженедельно"),
                    ("monthly", "ежемесячно"),
                ],
                default="ежедневно",
                max_length=20,
                verbose_name="Периодичность рассылки",
            ),
        ),
        migrations.AlterField(
            model_name="distribution",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "создана"),
                    ("launched", "запущена"),
                    ("completed", "завершена"),
                ],
                default="created",
                max_length=20,
                verbose_name="Статус рассылки",
            ),
        ),
    ]
