# Generated by Django 4.2 on 2024-10-26 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("distributions", "0014_alter_distribution_next_send_datetime_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attempt",
            name="status",
            field=models.CharField(
                choices=[("failed", "неудачно"), ("done", "выполнена")],
                default="failed",
                max_length=20,
                verbose_name="Статус рассылки",
            ),
        ),
        migrations.AlterField(
            model_name="distribution",
            name="next_send_datetime",
            field=models.CharField(
                blank=True,
                max_length=30,
                null=True,
                verbose_name="Дата следующей отправки",
            ),
        ),
        migrations.AlterField(
            model_name="distribution",
            name="period",
            field=models.CharField(
                choices=[
                    ("weekly", "еженедельно"),
                    ("monthly", "ежемесячно"),
                    ("daily", "ежедневно"),
                ],
                default="ежедневно",
                max_length=20,
                verbose_name="Периодичность рассылки",
            ),
        ),
    ]
