# Generated by Django 4.2 on 2024-10-26 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("distributions", "0015_alter_attempt_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attempt",
            name="last_attempt",
            field=models.DateTimeField(
                verbose_name="Дата и время последней попытки рассылки"
            ),
        ),
        migrations.AlterField(
            model_name="attempt",
            name="status",
            field=models.CharField(
                choices=[("done", "выполнена"), ("failed", "неудачно")],
                default="failed",
                max_length=20,
                verbose_name="Статус рассылки",
            ),
        ),
        migrations.AlterField(
            model_name="distribution",
            name="period",
            field=models.CharField(
                choices=[
                    ("monthly", "ежемесячно"),
                    ("weekly", "еженедельно"),
                    ("daily", "ежедневно"),
                ],
                default="ежедневно",
                max_length=20,
                verbose_name="Периодичность рассылки",
            ),
        ),
        migrations.AlterField(
            model_name="distribution",
            name="status",
            field=models.CharField(
                choices=[
                    ("completed", "завершена"),
                    ("created", "создана"),
                    ("launched", "запущена"),
                ],
                default="created",
                max_length=20,
                verbose_name="Статус рассылки",
            ),
        ),
    ]
