# Generated by Django 4.2 on 2024-10-26 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("distributions", "0019_alter_distribution_period"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attempt",
            name="status",
            field=models.CharField(
                choices=[("failed", "неудачно"), ("done", "выполнена")],
                default="failed",
                max_length=20,
                verbose_name="Статус рассылки",
            ),
        ),
        migrations.AlterField(
            model_name="distribution",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "создана"),
                    ("launched", "запущена"),
                    ("completed", "завершена"),
                ],
                default="created",
                max_length=20,
                verbose_name="Статус рассылки",
            ),
        ),
    ]
