# Generated by Django 4.2 on 2024-10-27 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("distributions", "0020_alter_attempt_status_alter_distribution_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="distribution",
            name="period",
            field=models.CharField(
                choices=[
                    ("weekly", "еженедельно"),
                    ("daily", "ежедневно"),
                    ("monthly", "ежемесячно"),
                ],
                default="ежедневно",
                max_length=20,
                verbose_name="Периодичность рассылки",
            ),
        ),
    ]
