# Generated by Django 4.2 on 2024-10-20 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Укажите фамилию, имя и отчество клиента",
                        max_length=150,
                        null=True,
                        verbose_name="Ф.И.О",
                    ),
                ),
                (
                    "client_email",
                    models.EmailField(
                        help_text="Укажите электронный адрес клиента",
                        max_length=254,
                        verbose_name="email клиента",
                    ),
                ),
                (
                    "comments",
                    models.CharField(
                        blank=True,
                        help_text="Комментарий",
                        max_length=150,
                        null=True,
                        verbose_name="Комментарий",
                    ),
                ),
            ],
            options={
                "verbose_name": "клиент",
                "verbose_name_plural": "клиенты",
                "ordering": ("id", "client_email"),
            },
        ),
    ]
