# Generated by Django 4.2 on 2024-10-21 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="client_email",
            field=models.EmailField(max_length=254, verbose_name="email клиента"),
        ),
        migrations.AlterField(
            model_name="client",
            name="comments",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="Комментарий"
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="name",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="Ф.И.О"
            ),
        ),
    ]
