# Generated by Django 4.2 on 2024-10-23 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("letters", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="letter",
            name="body",
            field=models.TextField(
                help_text="Укажите содержание письма", verbose_name="Сообщение"
            ),
        ),
        migrations.AlterField(
            model_name="letter",
            name="topic",
            field=models.CharField(
                help_text="Укажите тему письма",
                max_length=100,
                verbose_name="Тема письма",
            ),
        ),
    ]
