# Generated by Django 4.2 on 2024-10-24 19:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("letters", "0002_alter_letter_body_alter_letter_topic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="letter",
            name="body",
            field=models.TextField(
                help_text="Укажите содержание письма", verbose_name="Текст письма"
            ),
        ),
        migrations.AlterField(
            model_name="letter",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
    ]
